### ISSUE TITLE
Cannot extract FLIR Tau2 jpeg 

### ISSUE THREAD

**Issue by h-jia** [aloisklink/flirextractor#1]
Hi! Thanks for sharing. I have tested your test data and it works perfect. 

Unfortunately, for official FLIR datasets (sensor: FLIR Tau2), which is jpeg format, such as:
![FLIR_00001](https://user-images.githubusercontent.com/29906369/99902797-84783b80-2d14-11eb-9725-c60d6eee470a.jpeg)

I got the error of:
`cannot identify image file <_io.BytesIO object at 0x7f9090e81f40>`

I changed the `jpeg` to `jpg` but raised the same error.

Any suggestions will be much appreciated :)

**Comment by aloisklink** [comment]
Hi @h-jia,

I don't think this library will work on images from a FLIR Tau2 camera, as the images are missing a lot of metadata, such as Planck constants, which means the conversion from raw-data to temperature isn't easy to do. You can test this by running `exiftool TheNameOfYourFile.jpg`.

[flirpy](https://github.com/LJMUAstroecology/flirpy) might help if you want to convert the `.tiff` files in [this free official FLIR dataset]( https://www.flir.co.uk/oem/adas/adas-dataset-form/) to a temperature, but I believe they're only using a constant 0.04K per count conversion, which might not be very accurate.

I think the jpegs in the dataset have AGC (automatic gain control) setup, so it's probably impossible to get any temperatures out from them.

I know the error message is quite uninformative and confusing, so I'll improve it for next time.

**Comment by h-jia** [comment]
Hi @aloisklink,

Thanks for sharing. I will give it a try for your recommendations. 

Much appreciated!
